#!/bin/sh

if [[ "5.6" "7.0" "7.1" "7.2" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]
then
  PHP="php$1"
  CMD="$2"
  ARGS="${@:2}"
else
  PHP="php7.1"
  CMD="$1"
  ARGS="$@"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/$PHP" && pwd )"
IMG="docker-php/docker-$PHP"

if [[ $CMD == "build" ]]
then
  docker build -t "$IMG" "$DIR" --pull
else
  if [[ -f "$PWD/$CMD" ]]
  then
    ARGS="php $ARGS"
  fi

  docker run --rm -it -p 2375 \
   --name "$PHP" \
   --volume "$PWD":"$PWD" \
   --volume "$DIR"/cache/composer:/opt/composer \
   --env COMPOSER_HOME=/opt/composer/ \
   --workdir "$PWD" \
   "$IMG" $ARGS
fi

